version: "1.0"

services:
  morph:
    container_name: morph
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "10092:10092"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 10092
